/*  Cuarta consulta (histórico de tipos de indidencias)  */

SELECT 
	EXTRACT (YEAR FROM SM.FECHAINICIO_MUDANZA) AS FECHA_año,
	I.NOMBRE_INCIDENCIA AS TIPO,
	COUNT(I.ID_INCIDENCIA) AS CANTIDAD
FROM INCIDENCIA I
	INNER JOIN SERVICIO_MUDANZA SM ON I.ID_MUDANZA = SM.ID_MUDANZA
	WHERE I.ID_MUDANZA = SM.ID_MUDANZA 
	AND SM.FECHAINICIO_MUDANZA BETWEEN '2010-01-01' AND '2019-12-31' 
GROUP BY 
	EXTRACT (YEAR FROM SM.FECHAINICIO_MUDANZA),
	SM.FECHAINICIO_MUDANZA,
	I.NOMBRE_INCIDENCIA